services:
  # Panel Backend Web Service
  - type: web
    name: safestories-panel-backend
    env: node
    rootDir: panel-backend
    buildCommand: npm install
    startCommand: npx tsx src/index.ts
    plan: free
    autoDeploy: true
    envVars:
      - key: PORT
        value: 3003


